export const SET_CHARACTERS = 'SET_CHARACTERS'
export const SET_LOADING = 'SET_LOADING'
export const SET_PAGE = 'SET_PAGE'
export const SET_FILTER = 'SET_PAGE'
export const SET_FINDNAME = 'SET_FINDNAME'
